# Generated by Django 4.2.2 on 2023-07-13 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('info_course', models.TextField(verbose_name='Информация о Курсе')),
                ('img', models.ImageField(upload_to='img-course/', verbose_name='Фотография для курса')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Educationalcenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_center', models.CharField(max_length=50, verbose_name='Название центра')),
                ('img_center', models.ImageField(upload_to='img-center/', verbose_name='Фотография центра')),
                ('about_center', models.TextField(verbose_name='Иформация о Центре')),
                ('director', models.CharField(max_length=70, verbose_name='Директор')),
                ('director_img', models.ImageField(upload_to='', verbose_name='Фотография Директора')),
            ],
            options={
                'verbose_name': 'Учебный Центр',
                'verbose_name_plural': 'Учебные Центры',
            },
        ),
        migrations.CreateModel(
            name='ipModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50)),
                ('about_school', models.TextField(max_length=500)),
                ('director', models.CharField(max_length=100, verbose_name='Директор')),
                ('school_img', models.ImageField(upload_to='school-img/')),
                ('director_img', models.ImageField(null=True, upload_to='school_director_img')),
            ],
            options={
                'verbose_name': 'Школа',
                'verbose_name_plural': 'Школы',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('img', models.ImageField(upload_to='img-teachers/', verbose_name='Фотография')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('date_of_birth', models.DateTimeField(verbose_name='Дата Рождение')),
                ('email', models.EmailField(max_length=254)),
                ('course_teahcer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.course')),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учителья',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_img', models.ImageField(blank=True, upload_to='img-user/', verbose_name='Фотография Пользователя')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользовательи',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Краткое название')),
                ('news_img', models.ImageField(null=True, upload_to='news-img', verbose_name='Фоторафия для новости')),
                ('information', models.TextField(verbose_name='иформация')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('views', models.ManyToManyField(blank=True, related_name='просмотры', to='myapp.ipmodel')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Комент',
            },
        ),
    ]
