# Generated by Django 4.2.2 on 2023-07-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_img',
            field=models.ImageField(blank=True, default='person.png', upload_to='img-user', verbose_name='Фотография Пользователя'),
        ),
    ]
