# Generated by Django 4.2.2 on 2023-07-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_profile_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_img',
            field=models.ImageField(blank=True, upload_to='img-user', verbose_name='Фотография Пользователя'),
        ),
    ]
