# Generated by Django 4.2.2 on 2023-07-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_profile_user_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalcenter',
            name='course',
            field=models.ManyToManyField(related_name='Курсы', to='myapp.educationalcenter'),
        ),
    ]
