# Generated by Django 4.2.2 on 2023-07-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_educationalcenter_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalcenter',
            name='course',
            field=models.ManyToManyField(related_name='Курсы', to='myapp.course'),
        ),
    ]
