# Generated by Django 4.2.2 on 2023-07-22 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_educationalcenter_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educationalcenter',
            old_name='course',
            new_name='courses',
        ),
    ]
